name = "telegram-bot-cloudflare"
main = "src/bot/index.ts"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
CF_ACCOUNT_ID = "1244cf2ef2ea1cf95b7b95dc8188222c"
R2_BUCKET_NAME = "nhapiod-proxy"
R2_PUBLIC_URL = "https://pub-0a13ff58e0fb441aafab98f56637c326.r2.dev"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "NAMESPACE"
preview_id = "e025b27c36e4472dbfa62c21a543f742"
id = "c32219ae54c54b308b389c80e77850f7"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "nhapiod-proxy" 