name = "telegram-bot-cloudflare"
main = "src/bot/index.ts"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "NAMESPACE"
preview_id = "e025b27c36e4472dbfa62c21a543f742"
id = "c32219ae54c54b308b389c80e77850f7" 