name: PR Agent with Chutes AI

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Test Connection to Chutes AI
        run: |
          echo "Checking if secrets are set..."
          if [ -z "${{ secrets.CHUTES_AI_BASE_URL }}" ]; then echo "CHUTES_AI_BASE_URL is empty or not set"; exit 1; fi
          if [ -z "${{ secrets.CHUTES_AI_API_KEY }}" ]; then echo "CHUTES_AI_API_KEY is empty or not set"; exit 1; fi
          if [ -z "${{ secrets.CHUTES_AI_MODEL }}" ]; then echo "CHUTES_AI_MODEL is empty or not set"; exit 1; fi
          echo "All required secrets appear to be set. Pinging the Chutes AI endpoint..."
          echo "Base URL length: ${#CHUTES_AI_BASE_URL}"
          echo "API Key length: ${#CHUTES_AI_API_KEY}"
          echo "Model length: ${#CHUTES_AI_MODEL}"
          curl -v -X POST \
            ${{ secrets.CHUTES_AI_BASE_URL }}/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.CHUTES_AI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "${{ secrets.CHUTES_AI_MODEL }}",
              "messages": [{"role": "user", "content": "hello"}]
            }' --fail

      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          # --- This is the key fix ---
          # Tell PR-Agent to IGNORE any .pr_agent.toml file in the repository
          CONFIG__USE_REPO_SETTINGS_FILE: "false"

          # --- Standard GitHub token ---
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # --- Configuration for Chutes AI Endpoint ---
          OPENAI_API_KEY: ${{ secrets.CHUTES_AI_API_KEY }}
          OPENAI_API_BASE: "https://llm.chutes.ai/v1"
          OPENAI__KEY: ${{ secrets.CHUTES_AI_API_KEY }} # Keep for redundancy
          
          # --- Model Configuration ---
          CONFIG__MODEL: "openai/deepseek-ai/DeepSeek-R1-0528"
          CONFIG__FALLBACK_MODELS: '["openai/Qwen/Qwen3-235B-A22B-Thinking-2507"]'
          CONFIG__CUSTOM_MODEL_MAX_TOKENS: 128000
          
          # --- Connection & Timeout Fixes ---
          LITELLM_USE_REQUESTS: "true"
          CONFIG__AI_TIMEOUT: "120"
          
          # --- Automatic Tool Triggers ---
          github_action_config.auto_review: true
          github_action_config.auto_describe: true
          github_action_config.auto_improve: true
