name: PR Agent with Chutes AI

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pr_agent_job:
    # Do not run on PRs created by bots
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Test Connection to Chutes AI
        run: |
          echo "Checking if secrets are set..."
          if [ -z "${{ secrets.CHUTES_AI_BASE_URL }}" ]; then echo "CHUTES_AI_BASE_URL is empty or not set"; exit 1; fi
          if [ -z "${{ secrets.CHUTES_AI_API_KEY }}" ]; then echo "CHUTES_AI_API_KEY is empty or not set"; exit 1; fi
          if [ -z "${{ secrets.CHUTES_AI_MODEL }}" ]; then echo "CHUTES_AI_MODEL is empty or not set"; exit 1; fi
          echo "All required secrets appear to be set. Pinging the Chutes AI endpoint..."
          echo "Base URL length: ${#CHUTES_AI_BASE_URL}"
          echo "API Key length: ${#CHUTES_AI_API_KEY}"
          echo "Model length: ${#CHUTES_AI_MODEL}"
          curl -v -X POST \
            ${{ secrets.CHUTES_AI_BASE_URL }}/chat/completions \
            -H "Authorization: Bearer ${{ secrets.CHUTES_AI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "${{ secrets.CHUTES_AI_MODEL }}",
              "messages": [{"role": "user", "content": "hello"}]
            }' --fail

      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          # This is the standard GitHub token, required for the agent to interact with the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Your Chutes AI configuration
          OPENAI__API_BASE: ${{ secrets.CHUTES_AI_BASE_URL }}
          OPENAI_KEY: ${{ secrets.CHUTES_AI_API_KEY }}
          CONFIG__MODEL: ${{ secrets.CHUTES_AI_MODEL }}
          
          # For custom models, you must specify the maximum token limit
          CONFIG__CUSTOM_MODEL_MAX_TOKENS: 128000
          
          # --- Tell the agent what to do automatically on a new PR ---
          # Run the '/review' tool automatically on new PRs
          github_action_config.auto_review: true

          # Run the '/describe' tool automatically on new PRs
          github_action_config.auto_describe: true

          # Run the '/improve' tool automatically on new PRs
          github_action_config.auto_improve: true 